In [1]:
import numpy as np
import math

In [2]:
#QUESTION 1
a=np.random.random((10,1))
print (a)
m=a.mean()
print("mean is "+str(m))

[[0.46023961]
 [0.67782656]
 [0.94176288]
 [0.83582064]
 [0.28985807]
 [0.85493011]
 [0.35533583]
 [0.60891435]
 [0.82908191]
 [0.17215194]]
mean is 0.6025921889932554


In [3]:
#QUESTION 2
b=np.random.random((20,1))
print(b)
v=b.var()
print("variance is "+str(v))
s=b.std()
print("standard deviaation is "+str(s))

[[0.63856082]
 [0.35332734]
 [0.55746914]
 [0.61758128]
 [0.80973468]
 [0.32412647]
 [0.3718846 ]
 [0.18015245]
 [0.42145732]
 [0.93095533]
 [0.25004958]
 [0.85591672]
 [0.45583925]
 [0.7560509 ]
 [0.33936027]
 [0.73843852]
 [0.8861984 ]
 [0.22260538]
 [0.43805841]
 [0.87336419]]
variance is 0.05759179480902845
standard deviaation is 0.23998290524332863


In [4]:
#QUESTION 3
a=np.random.random((10,20))
b=np.random.random((20,25))

c=np.matmul(a,b)
print(c)
d=np.sum(c)
print("sum of all elements of new matrix is "+str(d))

[[4.91782508 5.44389592 4.88155652 3.7204656  3.27569053 5.31247616
  4.50374395 4.95083832 4.36637991 4.6528801  4.99850127 4.36265134
  4.48210546 5.35235645 4.02596065 4.26427113 4.22585715 4.41081867
  4.42368285 4.34450727 4.32619827 4.06755817 4.08068073 4.2759214
  3.53047981]
 [5.74204141 6.48726171 5.09960788 4.38419844 3.8986662  5.96937668
  5.61985842 5.5297611  5.32083023 4.79065802 6.35973258 4.36481809
  5.35114477 5.90810559 3.37462198 4.44553677 4.54439323 5.4170174
  4.83528378 5.32991756 5.31650644 4.7420678  5.443937   4.84999218
  4.02021917]
 [4.80919454 4.28855041 3.28040238 3.74267423 3.05756065 3.7068903
  3.39561278 3.86466374 3.22601883 3.8829889  4.52612418 3.2571272
  3.35810547 4.13658769 3.36105108 3.72726138 2.55432837 4.40655299
  4.34006828 3.5014669  2.88016681 3.53338595 3.47482393 3.01325171
  2.71665343]
 [6.45726557 4.96247196 4.93571188 4.31078689 3.80537446 5.39866715
  4.27240099 4.61469894 4.77211938 4.55735093 5.8170165  4.35350482
  3.557662

In [5]:
#QUESTION 4
a=np.random.random((10,1))
print(a)
b=[]
for i in range (0,10):
    x=1/(1+math.exp(-(a[i,0])))
    b.append(x)
print(b)

[[0.87477271]
 [0.04397628]
 [0.55759637]
 [0.02631481]
 [0.3751309 ]
 [0.57836039]
 [0.25765087]
 [0.2813636 ]
 [0.54898277]
 [0.48741823]]
[0.705737828504434, 0.5109922996533038, 0.6358962042125127, 0.506578321981372, 0.5926982012156271, 0.6406900439519957, 0.5640587357501892, 0.5698804973518178, 0.6338995529771948, 0.6194980443466156]
